accounts/urls.py
from django.contrib.auth import views 
#from .forms import LoginForm
from django.urls import include,path
from . import views

app_name='accounts'
urlpatterns = [
    #path('login',views.login,{'authentication_form':LoginForm}),
    #path('user_login/', views.user_login, name='user_login'),
    
    path('signup',views.signup,name="signup"),
    path('profile/',views.profile,name="profile"),
    path('home',views.home_page,name="home"),
    path('dashboard/<str:topic>',views.dashboard,name="dashboard"),
    path('tweets',views.tweets,name="tweets"),
    # path('search',views.search,name="search"),
    path('get_data',views.get_data,name="get_data"),
    path('create_report/<str:topic>',views.create_report,name="create_report"),
    path('save_topic/<str:topic>',views.save_topic,name="save_topic"),

     
     

]

project/urls.py
from django.contrib import admin
from django.urls import include,path

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
     
    path('', include('systemApp.urls',namespace='systemApp')),
    path('accounts/', include('django.contrib.auth.urls')), 
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
   
   
]
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

systemApp/urls.py
from django.urls import path
from . import views
app_name='systemApp'
urlpatterns = [
  
   path('',views.home_page,name="home"),
   path('tweets',views.tweets,name="tweets"),
   path('dashboard/<str:data>',views.dashboard,name="dashboard"),
   path('get_data',views.get_data,name="get_data"),
   
   
 
    

]

systemApp/models.py
from django.db import models

# Create your models here.

systemApp/views.py
from django.shortcuts import render
import requests
from . import DataRetrieval as dr
from . import Analysis as analysis
from . import SentimentModel as sentiment
import json
# Create your views here.
def home_page(request):
    request.session['search']="unknown"
    search=request.session.get('search','unknown')
    print(search)
    return render(request,'index.html')


def dashboard(request,data):
    #data retrieval function
    obj=dr.DataRetrieval()
    res=obj.get_all_reviews(data)

    res = sentiment.SentimentModel.get_sentiment(res)
    sent , sent_count = sentiment.SentimentModel.count_sentiment(res)
    labels_positive, counts_positive, labels_negative, counts_negative = analysis.Analysis.line_analysis(res)
    search=request.session.get('search','unknown')
    js = res.to_json(orient = 'records' , date_format = 'iso')
    request.session['res']=js
    context={'search':search,'sent':sent , 'sent_count':sent_count,'labels_positive':labels_positive, 'counts_positive':counts_positive
    , 'labels_negative':labels_negative, 'counts_negative':counts_negative}
    # if 'search' not in request.session:
    # if search == 'unknown':
    #     print(search)
    #     return render(request,'index.html')
    return render(request,"udashboard.html",context) 
def get_data(request):
    if request.method == 'POST':
         data = request.POST['search']
         request.session['search']=data
    else:
        data=request.session.get('search','unknown')
    # obj=dr.DataRetrieval()
    # res=obj.get_all_reviews(data)
    #search=request.session.get('search','unknown')
    if not request.session['search']:
       
        return render(request,'index.html')
    else:
          
         return dashboard(request,data)
  
# redirect to tweets page   
def tweets(request):
    search=request.session.get('search','unknown')
    response=request.session.get('res','unknown')
    res = json.loads(response)
    print(type(res))
    print(search)
    
    # if search == 'unknown':
    #     return render(request,'index.html')
    # else:    
    #response=requests.get('https://api.covid19api.com/countries').json()
    # if not request.session['search']:
    #   return render(request,'index.html')
    # else:
    return render(request,'utweets.html',{'search':search,'response':res})
def success(request,data):
    return render(request,'search.html',{'data':data})

systemApp/templates/index.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css'%}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/index_style.css'%}"/>

  <title>VISIONALYST</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg shadow-sm">
    <a class="navbar-brand" href="{% url 'systemApp:home' %}">
      <img src="{% static 'images/graph-analysis-1.png' %}" alt="" width="50.02" height="35.27" /></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon main-color">
        <i class="fas fa-align-justify"></i></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav m-auto">
        <li class="nav-item px-3 mb-sm-3 mb-lg-0">
          <a class="nav-link" href="{% url 'systemApp:home' %}">Home</a>
        </li>

        <li class="nav-item px-3 mb-sm-3 mb-lg-0"  >
            <a class="nav-link" href="#SERVICES">Services</a>
        </li>
        <li class="nav-item px-3 mb-sm-3 mb-lg-0"  >
            <a class="nav-link" href="#CONTACTUS">Contact us</a>
        </li>
      </ul>
      <a class=" nav-link" href="{% url 'accounts:signup' %}"><button class="btn btn-visionalyst rounded-pill px-5">Sign up</button></a>
      <a href="{% url 'login' %}" ><button class="btn btn-visionalyst rounded-pill px-5">Log in</button></a>
    </div>
  </nav>

  <header class="
        container
        text-center
        d-flex
        align-items-center
        justify-content-center
        py-5
        vh-100
      ">
    <div class="">
      <div class="slogan">
        <h1>VISIONALYST</h1>
        <p>Clear vision, better decision</p>
      </div>

      <form method="POST" class="search-bar pt-5" action="{% url 'systemApp:get_data' %}">
        {% csrf_token %}
        <div class="mb-3 m-auto position-relative">
          <input type="text" name='search' class="form-control form-control-lg rounded-pill" placeholder="#iphoneX or iphoneX" />
          <button type="submit" class="
                btn btn-visionalyst
                search-btn
                header-btn
                shadow-lg
                text-center
                rounded-pill
                mt-3
                px-4
              ">
            <img src="{% static 'images/loupe-1.png' %}" alt="" />
          </button>
        </div>
      </form>
    </div>
  </header>
  <!-- ------------------------------------end of header section------------------------------------- -->
  <!-- -------------------------------------start of service----------------------------------------- -->
  <section id="SERVICES" class="services container my-5">
    <div class="row">
      <div class="col-lg-6 services-content py-5">
        <h2 class="pb-3">WHAT WE DO</h2>
        <div>
          <p class="text-muted">
            Although most of us use social media platforms to convey our
            personal feelings and opinions for the world to see, one of the
            biggest challenges lies in understanding the 'sentiments' behind
            social media posts.
          </p>
          <p class="text-muted">
            Understanding people’s emotions has become more essential and a
            challenge for businesses since people express their feelings more
            openly than ever before.
          </p>
          <p class="text-muted">
            By translating text (social media conversations, tweets, or posts)
            allows stakeholders to listen attentively to their customers to
            meet their needs.
          </p>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="image">
          <img class="img-fluid" src="{% static 'images/Visual data-bro.png' %}" alt="" width="579.37px" height="600.58" />
        </div>
      </div>
    </div>
    <div class="row my-5">
      <div class="col-lg-6 order-lg">
        <img class="img-fluid" src="{% static 'images/Analysis-bro.svg' %}" alt="" width="579.37px" height="600.58" />
      </div>
      <div class="col-lg-6 services-content py-5">
        <div class="py-5">
          <h2>WHAT WE FOCUS ON</h2>
          <p class="text-muted">
            Helping products companies to know what consumers think about
            their products, customer services, and that in return will help
            them to know what they lack, and what they need to improve to make
            their products and services meets consumers’ needs
          </p>
        </div>
      </div>
    </div>
  </section>
  <!-- ------------------------------------------end of services---------------------------------- -->
  <!-- ------------------------------------start of main goals section--------------------------------------- -->
  <section ID="GOALS" class="goals my-5 vh-100">
    <div class="container text-center">
      <h3 class="font-weight-bold py-5">Main Goals</h3>
      <div class="row">
        <div class="col-md-4 mb-5  goal">
          <i class="fa fa-crosshairs pb-3"></i>
          <h4>precision</h4>
          <p class="text-muted">
            Providing you with accurate precise insights about the products you desire without worrying of what people really think about it, as it will be in front of your eyes
          </p>
        </div>
        <div class="col-md-4 goal mb-5">
          <i class="fa fa-rocket pb-3"></i>
          <h4>Speed</h4>
          <p class="text-muted">
            You do not have to wait forever any more, just one click and insights of what you are looking for will be in your grasp within moments  
          </p>
        </div>
        <div class="col-md-4 goal mb-5">
          <i class="far fa-chart-bar pb-3"></i>
          <h4>Real time analysis</h4>
          <p class="text-muted">
            Helping you follow current trends and what people think about the products by providing real time tweets and
            reviews
          </p>
        </div>
      </div>
    </div>
  </section>
  <!-- ------------------------------------------------end of my goals------------------------------------------------- -->
  <footer ID="CONTACTUS" class="  contact position-relative">
    <div class="container">
      <div class="row pt-5">
        <div class="col-md-6 mb-5">
          <h3 class="pb-3">Become a visionalyst</h3>
          <p>
            become a visionalyst and get latest tweets and social media posts
            about desired topics in your profile.
          </p>
          <button class="btn btn-visionalyst">become a visionalyst</button>
        </div>
        <div class="col-md-6 mb-5 feed-back">
          <h3 class="pb-3">We looking for your feedback!</h3>
          <textarea name="" id="" cols="30" rows="4" class="form-control bg-light"></textarea>
        </div>
      </div>
      <div class="social-media text-center">
        <div class="social-icons py-5">
          <i class="fab fa-facebook px-2"></i>
          <i class="fab fa-twitter px-2"></i>
          <i class="fab fa-instagram px-2"></i>
          <i class="fab fa-github px-2"></i>
        </div>
      </div>
    </div>
    <div class="copyrights"></div>
  </footer>
  
  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/index.umd.js' %}"></script>
  
</body>

</html>

systemApp/templates/search.html
<html>
  <head>
      <title>search</title>
  </head>
  <body>
      <h1>{{data}}</h1>
  </body>
</html>

systemApp/templates/udashboard.html
{% load static %}
{% load bootstrap4 %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/index_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard_style.css' %}">
    <title>Dashboards</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-color shadow d-flex justify-content-between">
        <a class="navbar-brand" href="{% url 'systemApp:home' %}">
            <img src="{% static 'images/graph-analysis-1.png' %}" alt="" width="30.02" height="25.27" /></a>

        <div class="navbar-nav ml-5">
            <p class="nav-item ml-md-5 mb-0">{{search}}</p>
            <!--el kelma elly 3ml search 3leha -->
        </div>

        <a href="{% url 'systemApp:tweets' %}"
            class="btn btn-visionalyst rounded-pill px-lg-5 px-sm-2 nav-btn">Tweets</a>
    </nav>

    <h2 class="text-center py-5 font-weight-bold main-color">DASHBOARDS</h2>
    <div class="container">
        <div class="row d-flex justify-content-center align-items-center">

            <div class="col-md-8 mb-5">
                <div class="card border-0 rounded-lg shadow-sm">
                    <div class="card-body">
                        <canvas id="myLineChart" width="400" height="180"></canvas>
                    </div>
                </div>
            </div>

            <div class="col-md-4 mb-5">
                <div class="card border-0 rounded-lg shadow-sm">
                    <div class="card-body">
                        <canvas id="myDoughnutChart" width="400" height="400"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/chart.min.js' %}"></script>
    <script>
        var ctx1 = document.getElementById('myLineChart').getContext('2d');
        var myBarChart = new Chart(ctx1, {
            type: 'line',
            data: {
                labels: {{ labels_positive| safe}},
        datasets: [{
            label: 'Positive',
            data: {{ counts_positive| safe}},
            backgroundColor: ['#36a2eb'],
            borderWidth: 2,
            borderColor: '#36a2eb'
                },
        {
            label: 'Negative',
            data: {{ counts_negative| safe}},
            backgroundColor: ['#dc3545'],
            borderWidth: 2,
            borderColor: '#dc3545'
                }]

            },
        options: {
            plugins: {
                title: {
                    display: true,
                        text: 'Sentiment over years',
                            font: { size: 20 }
                },
                legend: {
                    position: 'right',
                        borderColor: "#36a2eb"
                }
            }
        }
        });

        var ctx4 = document.getElementById('myDoughnutChart').getContext('2d');
        var myPieChart = new Chart(ctx4, {
            type: 'doughnut',
            data: {
                labels: {{ sent| safe}},
        datasets: [
            {
                label: '# of Votes',
                data: {{ sent_count| safe}},
            backgroundColor: [
                '#36a2eb','#dc3545'
            ],
            borderColor: [
            '#36a2eb','#dc3545'
            ],
            borderWidth: 1
            }]
    },
        options: {
            responsive: true,
                plugins: {
                legend: {
                    position: 'top',
            },
                title: {
                    display: true,
                        text: 'Predicted sentiment'
                }
            }

        }
});
    </script>

</body>

</html>

systemApp/templates/utweets.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width= , initial-scale=1.0" />

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/all.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/tweets_style.css'%}" />
    <title>tweets</title>
</head>

<body>



    <nav class="navbar navbar-expand-lg navbar-color shadow d-flex justify-content-between">
        <a class="navbar-brand" href="{% url 'systemApp:home' %}">
            <img src="{% static 'images/graph-analysis-1.png' %}" alt="" width="30.02" height="25.27" /></a>

        <div class="navbar-nav m-auto">
            <p class="nav-item mb-0">{{search}}</p>
            <!--el kelma elly 3ml search 3leha -->
        </div>

    </nav>

    <div class="container py-4">
        <div class="row">
            {% for c in response%}
            <div class="col-md-6 col-lg-4 mb-5">
                <div class="card" style="height: 300px;">
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <div class=" text-center">
                                <h5 class="text-primary">{{c.name}}</h5>
                                <!-- <h6 class=" mb-2 text-muted">
                                    Posted {{c.date}}
                                </h6> -->
                            </div>
                            <div class="social-icon mb-4 pr-3">
                                <i class="{% if c.platform == twitter %} fab fa-twitter {% else %} fab fa-amazon {% endif %}"></i>
                            </div>
                        </div>
                        <div class="do-nicescrol">
                            <P class="card-text  overflow-auto" style="height: 120px;">{{c.review}}
                            </P>
                        </div>
                        <hr>
                        <div class="text-center mt-3">
                            <span class="{% if c.sentiment == 'positive' %} text-primary {% else %} text-danger {% endif %}" style="font-size: 18px;">{{c.sentiment}}</span>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor%}
        </div>
    </div>


    <script src="{% static 'js/jquery-3.2.1.slim.min.js'%}"></script>
    <script src="{% static 'js/popper.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/jquery.nicescroll.min.js'%}"></script>
    <script>$(".do-nicescrol").nicescroll();</script>
</body>

</html>