accounts/urls.py
from django.contrib.auth import views 
#from .forms import LoginForm
from django.urls import include,path
from . import views

app_name='accounts'
urlpatterns = [
    #path('login',views.login,{'authentication_form':LoginForm}),
    #path('user_login/', views.user_login, name='user_login'),
    
    path('signup',views.signup,name="signup"),
    path('profile/',views.profile,name="profile"),
    path('home',views.home_page,name="home"),
    path('dashboard/<str:topic>',views.dashboard,name="dashboard"),
    path('tweets',views.tweets,name="tweets"),
    # path('search',views.search,name="search"),
    path('get_data',views.get_data,name="get_data"),
    path('create_report/<str:topic>',views.create_report,name="create_report"),
    path('save_topic/<str:topic>',views.save_topic,name="save_topic"),

     
     

]

project/urls.py
from django.contrib import admin
from django.urls import include,path

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
     
    path('', include('systemApp.urls',namespace='systemApp')),
    path('accounts/', include('django.contrib.auth.urls')), 
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
   
   
]
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Topic(models.Model):
    topic_name=models.CharField(max_length=100)
    created_at=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.topic_name

class CustomUser(AbstractUser):
    job_title=models.CharField(max_length=100)
    phone_number=models.CharField(max_length=20)
    age=models.IntegerField()
    SEX_FEMALE = 'F'
    SEX_MALE = 'M'

    SEX_OPTIONS = (
        (SEX_FEMALE, 'Female'),
        (SEX_MALE, 'Male'),
        
    )
    gender = models.CharField(max_length=1, choices=SEX_OPTIONS)

    topics=models.ManyToManyField(Topic)
  

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.forms import widgets,ChoiceField
from .models import CustomUser
CHOICE_LIST = [
    ('', '--Select gender--'), # replace the value '----' with whatever you want, it won't matter
     ('M','Male'),
        ('F','Female'),
]

class CustomUserForm(UserCreationForm):
    password1=forms.CharField(label=(""),widget=forms.PasswordInput(attrs={'class':'form-control form-control-md rounded-pill text-center','id':'exampleInputPassword1','placeholder':'Password1'}))
    password2=forms.CharField(label=(""),widget=forms.PasswordInput(attrs={'class':'form-control form-control-md rounded-pill text-center','id':'exampleInputPassword1','placeholder':'Confirm password'}))
    gender = ChoiceField(choices=CHOICE_LIST,label=(""),widget=forms.Select(attrs={'class':'form-select form-control form-control-md rounded-pill text-center','id':'inputGroupSelect01','placeholder':'Gender'}))
    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)

        for fieldname in ['username','email', 'password1', 'password2','job_title','phone_number','age','gender']:
            self.fields[fieldname].help_text = None
            self.fields[fieldname].label = ""
    class Meta:
        model=CustomUser
        fields=['username','email','password1','password2','job_title','phone_number','age','gender']
        widgets={
            'username':forms.TextInput(attrs={'class':'form-control form-control-md rounded-pill text-center','id':'exampleInputPassword1','placeholder':'username'}),
             'email':forms.TextInput(attrs={'class':'form-control form-control-md rounded-pill text-center','aria-describedby':'emailHelp','id':'exampleInputEmail1','placeholder':'Email@gmail.com' }),
             'job_title':forms.TextInput(attrs={'class':'form-control form-control-md rounded-pill text-center','id':'exampleInputPassword1','placeholder':'Job title'}),
             'phone_number':forms.TextInput(attrs={'class':'form-control form-control-md rounded-pill text-center','id':'exampleInputPassword1','placeholder':'Phone number'}),
           # 'gender':forms.Select(attrs={'class':'form-select form-control form-control-md rounded-pill text-center','id':'inputGroupSelect01','placeholder':'Gender'}),
            'age':forms.NumberInput(attrs={'class':'form-control form-control-md rounded-pill text-center ml-3','id':'exampleInputPassword1','placeholder':'Age'})
             
        }
class LoginForm(AuthenticationForm):
       username=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control form-control rounded-pill w-75'}))
       password=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control form-control rounded-pill w-75'}))

accounts/views.py
from django.contrib.auth import authenticate,login
from django.shortcuts import render,redirect
from .forms import CustomUserForm
from .models import CustomUser,Topic
import requests
from django.contrib.auth.decorators import login_required
from . import DataRetrieval as dr
from . import Analysis as analysis
from . import SentimentModel as sentiment
from sklearn.pipeline import Pipeline
from joblib import load
import json
from . import AspectsAnalysis as AS
from django.contrib import messages
#pipeline = load("visionalyst_classifier_dt.joblib")

# Create your views here.
@login_required(login_url="/accounts/login/")
def home_page(request):
    return render(request,'home.html')

def get_data(request):
    if request.method == 'POST':
         data = request.POST['search']
         request.session['search']=data
    else:
        data=request.session.get('search','unknown')
    # obj=dr.DataRetrieval()
    # res=obj.get_all_reviews(data)

    # res=sentiment.SentimentModel.get_sentiment(res)
    # js = res.to_json(orient = 'records' , date_format = 'iso')
    # request.session['res']=js
    if not request.session['search']:
       
        return render(request,'home.html')
    else:
          
         return dashboard(request,data)
    

@login_required(login_url="/accounts/login/")
def tweets(request):
  #response=requests.get('https://api.covid19api.com/countries').json()
  response=request.session.get('res','unknown')
  search=request.session.get('search','unknown')
  res = json.loads(response)
  print(type(res))
  return render(request,'tweets.html',{'search':search,'response':res })

 

@login_required(login_url="/accounts/login/")
def dashboard(request,data):
    #res=request.session.get('res','unknown')
    obj=dr.DataRetrieval()
    res=obj.get_all_reviews(data)
    hashtag,hash_count=analysis.Analysis.hashtag_analysis(res)
    
    top_hash_count=max(hash_count)
    top_hash=hashtag[hash_count.index(top_hash_count)]
    
    
    location,loc_count = [],[]
    location,loc_count=analysis.Analysis.location_analysis(res)
    top_loc_count=max(loc_count)
    top_location=location[loc_count.index(top_loc_count)]
    
    #labels_wordcloud, counts_wordlcoud =analysis.Analysis.wordcloud(res)
    res = sentiment.SentimentModel.get_sentiment(res)
    
    sent , sent_count = sentiment.SentimentModel.count_sentiment(res)
    
    labels_positive, counts_positive, labels_negative, counts_negative = analysis.Analysis.line_analysis(res)
    #print(labels_positive, counts_positive, labels_negative, counts_negative)
    # print(labels_positive,counts_positive, labels_negative, counts_negative)
    search=request.session.get('search','unknown')
    js = res.to_json(orient = 'records' , date_format = 'iso')
    request.session['res']=js
    obj=AS.AspectsAnalysis()
    # print(search) 
    noun, pos, neg=obj.get_aspects(res)
    top_aspects_count = max(pos)
    top_aspect = noun[pos.index(top_aspects_count)]
#'labels_wordcloud':labels_wordcloud,'counts_wordlcoud':counts_wordlcoud,
    context={'hashtag':hashtag,'hash_count':hash_count,'top_hash':top_hash,'top_hash_count':top_hash_count,
    'top_location':top_location,'top_loc_count':top_loc_count,
    'location':location,'loc_count':loc_count,'sent':sent,'sent_count':sent_count
    ,'labels_positive':labels_positive,'counts_positive': counts_positive,
     'labels_negative':labels_negative, 'counts_negative':counts_negative,
     'noun':noun,'pos': pos,'neg': neg,'top_aspects_count':top_aspects_count,'top_aspect':top_aspect,
     'search':search}
    return render(request,"dashboard.html",context) 


def signup(request):
    
    if request.method=="POST":
            user_form=CustomUserForm(request.POST)        
            if  user_form.is_valid():
                user_form.save()
                username=user_form.cleaned_data['username']
                password=user_form.cleaned_data['password1']
                user=authenticate(username=username,password=password)
                login(request,user)
                return render(request,'home.html')
            

    else:
            user_form=CustomUserForm()
            

    context={'user':request.user,'user_form':user_form}
    return render(request,'registration/signup.html',context)

def create_report(request,topic):
    request.session['search']=topic
    return get_data(request)
    
# def user_login(request):
    # if request.method == 'POST':
    #     # Process the request if posted data are available
    #     username = request.POST['username']
    #     password = request.POST['password']
    #     # Check username and password combination if correct
    #     user = authenticate(username=username, password=password)
    #     if user is not None:
    #         # Save session as cookie to login the user
    #         login(request, user)
    #         # Success, now let's login the user.
    #         return render(request, 'profile.html')
    #     else:
    #         # Incorrect credentials, let's throw an error to the screen.
    #         return render(request, 'registration/login.html', {'error_message': 'Incorrect username and / or password.'})
    # else:
    #     # No post data availabe, let's just show the page to the user.
    #     return render(request, 'registration/login.html')   

@login_required(login_url="/accounts/login/")
def profile(request):
    user=request.user
    #profile=Profile.objects.get(user=request.user)
    #user=CustomUserForm.objects.all()
    #user=CustomUser.objects.get(user=request.user)
    #profile=Profile.objects.all()
    context={'user':user}
    return render(request,"profile.html",context)

def save_topic(request,topic):
    user=request.user
    new_user=CustomUser.objects.get(username=user.username)
    #topics_list=Topic.objects.all()
    topics_list=new_user.topics.all()
    new_topic=Topic()
    new_topic.topic_name=topic
    llist = []
    for t in topics_list:
        llist.append(t.topic_name)
    if topic in llist:
        print('ohhh')
        # new_topic.save()
        # new_user.topics.add(new_topic)
        # new_user.save()
    else:
        new_topic.save()
        new_user.topics.add(new_topic)
        new_user.save()
         


  
         
        
    
    # user=request.user
    # new_user=CustomUser.objects.get(username=user.username)
    # new_topic=Topic()
    # new_topic.topic_name=topic
    # new_topic.save()
    # new_user.topics.add(new_topic)
    # new_user.save()
    return render(request,'profile.html')

accounts/templates/dashboard.html
{% load static %}
{% load bootstrap4 %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/index_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard_style.css' %}">
    <title>Dashboards</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-color shadow d-flex justify-content-between">
        <a class="navbar-brand" href="{% url 'accounts:home' %}">
            <img src="{% static 'images/graph-analysis-1.png' %}" alt="" width="30.02" height="25.27" /></a>

        <div class="navbar-nav">
            <p class="nav-item mb-0">

                {{search}}



            </p>


            <!--el kelma elly 3ml search 3leha -->
        </div>
        <div>
            <a href="{% url 'accounts:save_topic' search %} "
                class="btn btn-visionalyst rounded-pill px-lg-5 px-sm-2 nav-btn">Save
                report</a>
            <a href="{% url 'accounts:tweets' %} "
                class="btn btn-visionalyst rounded-pill px-lg-5 px-sm-2 nav-btn">tweets</a>
        </div>
    </nav>
    <h2 class="text-center py-5 font-weight-bold main-color">DASHBOARDS</h2>
    <div class="container">
        <div class="row">

            <div class="col-md-8 mb-3">
                <div class="card border-0 rounded-lg shadow-lg" style="height:400px">
                    <canvas id="myLineChart"></canvas>
                </div>
            </div>
            <div class="col-md-4 mb-3">
                <div class="card d-flex justify-content-center border-0 rounded-lg shadow-lg h-100">
                    <h4 class="text-center py-4 font-weight-bold text-muted">TRENDINGS</h4>
                    <div class="list-group list-group-flush text-muted trends">
                        <div class="list-group-item d-flex justify-content-between">
                            <i class="fas fa-chart-pie "></i>
                            <div class="  text-right">
                                <p class=" trend-text text-muted my-0">{{top_aspects_count}}</p>
                                <p class="my-0">{{top_aspect}}</p>
                            </div>
                        </div>
                        <div class="list-group-item d-flex justify-content-between">
                            <i class="fab fa-slack-hash"></i>
                            <div class="  text-right">
                                <p class="trend-text my-0 text-muted">{{top_hash_count}}</p>
                                <p class="my-0">{{top_hash}}</p>
                            </div>
                        </div>
                        <div class="list-group-item d-flex justify-content-between">
                            <i class="fas fa-globe-africa"></i>
                            <div class="  text-right">
                                <p class=" trend-text my-0 text-muted">{{top_loc_count}}</p>
                                <p class="my-0">{{top_location}}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4 mb-5">
                <div class="card border-0 rounded-lg shadow-lg">
                    <div class="card-body" style="height:400px">
                        <canvas id="myDoudhuntChart"></canvas>
                    </div>
                </div>
            </div>

            <div class="col-md-8 mb-5 ">
                <div class="card border-0 rounded-lg shadow-lg ">
                    <div class="card-body" style="height:400px">
                        <canvas id="myMixedBarChart"></canvas>
                    </div>
                </div>
            </div>







            <div class="col-md-6 mb-5">
                <div class="card border-0 rounded-lg shadow-lg">
                    <div class="card-body" >
                        <canvas  width="400" height="400"  id="myBarChart"></canvas>
                    </div>
                </div>
            </div>



            <div class="col-md-6 mb-5">
                <div class="card border-0 rounded-lg shadow-lg">
                    <div class="card-body" >
                        <canvas width="400" height="400"  id="myBarChart2"></canvas>
                    </div>
                </div>
            </div>

            

            <!-- <div class="col-md-12 mb-5 ">
                <div class="card border-0 rounded-lg shadow-lg ">
                    <div class="card-body">
                        <canvas id="myWordcloudChart" width="400" height="400"></canvas>
                    </div>
                </div>
            </div> -->
            


        </div>
    </div>
    <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src=" https://unpkg.com/chart.js@3.3.2/dist/chart.js "></script>
    <script src="{% static 'js/index.umd.js' %}"></script>
    <!-- <script src="{% static 'js/dashboard.js' %}"></script> -->
    <!-- {{noun}}
    {{sent_noun}}
    {{noun_count}} -->
    <!-- {{labels_positive}}
    {{counts_positive}}
    {{hashtag}} -->
    <!-- {{noun}}
    {{sent_noun}}
    {{noun_count}} -->
    <script>

        console.log(typeof (d))
        var ctx1 = document.getElementById('myLineChart').getContext('2d');
        var myLineChart = new Chart(ctx1, {
            type: 'line',
            data: {
                labels: {{ labels_positive| safe}},
        datasets: [{
            label: 'Positive',
            data: {{ counts_positive| safe}},
            backgroundColor: ['#36a2eb'],
            borderWidth: 2,
            borderColor: '#36a2eb'
                },
        {
            label: 'Negative',
            data: {{ counts_negative| safe}},
            backgroundColor: ['#ff0000'],
            borderWidth: 2,
            borderColor: '#ff0000'
                }]

            },
        options: {
            responsive:true,
            plugins: {
                title: {
                    display: true,
                        text: 'Sentiment over monthes (2021)',
                            font: { size: 20 }
                },
                legend: {
                    position: 'right',
                        borderColor: "#36a2eb"
                }
            }
        }
        });

        var ctx2 = document.getElementById('myBarChart').getContext('2d');
        var myLineChart = new Chart(ctx2, {
            type: 'pie',
            data: {
                labels: {{ hashtag| safe}},
        datasets: [{
            label: "# hashtag",
            data: {{ hash_count| safe}},
            backgroundColor: [
            'rgba(255, 99, 132, 1)',
            'rgba(54, 162, 235, 1)',
            'rgba(255, 206, 86, 1)',
            'rgba(75, 192, 192, 1)',
            'rgba(153, 102, 255, 1)',
            'rgba(255, 159, 64, 1)'
        ],
            // borderColor: [
            //     'rgba(146, 277, 169, 1)',
            //     'rgba(54, 162, 235, 1)',
            //     'rgba(255, 206, 86, 1)',
            //     'rgba(75, 192, 192, 1)',
            //     'rgba(1 53, 102, 255, 1)',
            //     'rgba(255, 159, 64, 1)'
            // ],
            // borderWidth:3
        }]
    },
        options: {
            responsive:true,
            plugins: {
                title: {
                    display: true,
                        text: 'Top 10 hashtags mentioned',
                            font: { size: 20 }
                },
                legend: {
                    position: 'right',
                        borderColor: "#36a2eb"
                }
            }

        }
});
        var ctx3 = document.getElementById('myBarChart2').getContext('2d');
        var mybarChart = new Chart(ctx3, {
            type: 'bar',
            data: {
                labels: {{ location| safe}},
        datasets: [
            {
                label: "# location",
                data: {{ loc_count| safe}},
            backgroundColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
            }]
    },
        options: {
            responsive:true,
            plugins: {
                title: {
                    display: true,
                        text: 'Top 10 locations mentioned',
                            font: { size: 20 }
                },
                legend: {
                    display:false   
                }
            },
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
});
        var ctx4 = document.getElementById('myDoudhuntChart').getContext('2d');
        var myPieChart = new Chart(ctx4, {
            type: 'doughnut',
            data: {
                labels:['Positive','Negative'],
        datasets: [
            {
                label: '# of Votes',
                data: {{ sent_count| safe}},
            backgroundColor: ['#36a2eb','#ff0000'],

            borderColor: ['#36a2eb','#ff0000'],
            borderWidth: 1
            }]
    },
        options: {
            responsive: true,
                plugins: {
                legend: {
                    position: 'top',
            },
                title: {
                    display: true,
                        text: 'Predicted sentiment',
                            font: { size: 20 },
                }
            }

        }
});

        var ctx8 = document.getElementById('myMixedBarChart').getContext('2d');
        var myMixedChart = new Chart(ctx8, {
            type: 'bar',
            data: {
                labels: {{ noun| safe}},
        datasets: [{
            label: 'Positive',
            data: {{ pos| safe}},
            backgroundColor: ['#36a2eb'],
            borderWidth: 2,
            borderColor: '#36a2eb'
                        },
        {
            label: 'Negative',
            data: {{ neg| safe}},
            backgroundColor: ['#ff0000'],
            borderWidth: 2,
            borderColor: '#ff0000'
                        }]
        
                    },
        options: {
            responsive:true,
            plugins: {
                title: {
                    display: true,
                        text: 'Top 10 aspects mentioned',
                            font: { size: 20 }
                },
                legend: {
                    position: 'right',
                        borderColor: "#36a2eb"
                }
            }

        }
});











    </script>
</body>

</html>

accounts/templates/home.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css'%}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/index_style.css'%}"/>

  <title>VISIONALYST</title>
</head>

<body onload="loadClassifier()">
  <nav class="navbar navbar-expand-lg shadow-sm fixed-top navbar-white">
    <a class="navbar-brand" href="{% url 'accounts:home' %}">
      <img src="{% static 'images/graph-analysis-1.png' %}" alt="" width="50.02" height="35.27" /></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon main-color">
        <i class="fas fa-align-justify"></i></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav m-auto">
        <li class="nav-item px-3 mb-sm-3 mb-lg-0">
          <a class="nav-link" href="{% url 'accounts:home' %}">Home</a>
        </li>

        <li class="nav-item px-3 mb-sm-3 mb-lg-0" >
            <a class="nav-link" href="#SERVICES">Services</a>
        </li>
        <li class="nav-item px-3 mb-sm-3 mb-lg-0"  >
          <a class="nav-link" href="#CONTACTUS">contact us</a>
      </li>
        <li class="nav-item px-3 mb-sm-3 mb-lg-0"  >
          <a class=" nav-link" href="{% url 'accounts:profile' %}">profile</a>
      </li>
        </ul>

      <a href="{% url 'logout' %}" ><button class="btn btn-visionalyst rounded-pill px-5">Log out</button></a>
    </div>
  </nav>

  <header class="
        container
        text-center
        d-flex
        align-items-center
        justify-content-center
        py-5
        vh-100
      ">
    <div class="">
      <div class="slogan">
        <h1>VISIONALYST</h1>
        <p>Clear vision, better decision</p>
      </div>

      <form method="POST" class="search-bar pt-5" action="{% url 'accounts:get_data' %}">
        {% csrf_token %}
        <div class="mb-3 m-auto position-relative">
          <input type="text" name='search' class="form-control form-control-lg rounded-pill" placeholder="#iphoneX or iphoneX" />
          <button type="submit" class="
                btn btn-visionalyst
                search-btn
                header-btn
                shadow-lg
                text-center
                rounded-pill
                mt-3
                px-4
              ">
            <img src="{% static 'images/loupe-1.png' %}" alt="" />
          </button>
        </div>
      </form>
    </div>
  </header>
  <!-- ------------------------------------end of header section------------------------------------- -->
  <!-- -------------------------------------start of service----------------------------------------- -->
  <section id="SERVICES" class="services container my-5">
    <div class="row">
      <div class="col-lg-6 services-content py-5">
        <h2 class="pb-3">WHAT WE DO</h2>
        <div>
          <p class="text-muted">
            Although most of us use social media platforms to convey our
            personal feelings and opinions for the world to see, one of the
            biggest challenges lies in understanding the 'sentiments' behind
            social media posts.
          </p>
          <p class="text-muted">
            Understanding people’s emotions has become more essential and a
            challenge for businesses since people express their feelings more
            openly than ever before.
          </p>
          <p class="text-muted">
            By translating text (social media conversations, tweets, or posts)
            allows stakeholders to listen attentively to their customers to
            meet their needs.
          </p>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="image">
          <img class="img-fluid" src="{% static 'images/Visual data-bro.png' %}" alt="" width="579.37px" height="600.58" />
        </div>
      </div>
    </div>
    <div class="row my-5">
      <div class="col-lg-6 order-lg">
        <img class="img-fluid" src="{% static 'images/Analysis-bro.svg' %}" alt="" width="579.37px" height="600.58" />
      </div>
      <div class="col-lg-6 services-content py-5">
        <div class="py-5">
          <h2>WHAT WE FOCUS ON</h2>
          <p class="text-muted">
            Helping products companies to know what consumers think about
            their products, customer services, and that in return will help
            them to know what they lack, and what they need to improve to make
            their products and services meets consumers’ needs
          </p>
        </div>
      </div>
    </div>
  </section>
  <!-- ------------------------------------------end of services---------------------------------- -->
  <!-- ------------------------------------start of main goals section--------------------------------------- -->
  <section ID="GOALS" class="goals my-5 vh-100">
    <div class="container text-center">
      <h3 class="font-weight-bold py-5">Main Goals</h3>
      <div class="row">
        <div class="col-md-4 mb-5  goal">
          <i class="fa fa-crosshairs pb-3"></i>
          <h4>precision</h4>
          <p class="text-muted">
            Providing you with accurate precise insights about the products you desire without worrying of what people really think about it, as it will be in front of your eyes
          </p>
        </div>
        <div class="col-md-4 goal mb-5">
          <i class="fa fa-rocket pb-3"></i>
          <h4>Speed</h4>
          <p class="text-muted">
            You do not have to wait forever any more, just one click and insights of what you are looking for will be in your grasp within moments  
          </p>
        </div>
        <div class="col-md-4 goal mb-5">
          <i class="far fa-chart-bar pb-3"></i>
          <h4>Real time analysis</h4>
          <p class="text-muted">
            Helping you follow current trends and what people think about the products by providing real time tweets and
            reviews
          </p>
        </div>
      </div>
    </div>
  </section>
  <!-- ------------------------------------------------end of my goals------------------------------------------------- -->
  <footer ID="CONTACTUS" class="contact position-relative">
    <div class="container">
      <div class="row pt-5">
        <div class="col-md-6 mb-5">
          <h3 class="pb-3">Become a visionalyst</h3>
          <p>
            become a visionalyst and get latest tweets and social media posts
            about desired topics in your profile.
          </p>
          <button class="btn btn-visionalyst">become a visionalyst</button>
        </div>
        <div class="col-md-6 mb-5 feed-back">
          <h3 class="pb-3">We looking for your feedback!</h3>
          <textarea name="" id="" cols="30" rows="4" class="form-control bg-light"></textarea>
        </div>
      </div>
      <div class="social-media text-center">
        <div class="social-icons py-5">
          <i class="fab fa-facebook px-2"></i>
          <i class="fab fa-twitter px-2"></i>
          <i class="fab fa-instagram px-2"></i>
          <i class="fab fa-github px-2"></i>
        </div>
      </div>
    </div>
    <div class="copyrights"></div>
  </footer>
  
  <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>

accounts/templates/output.html
{{res}}